heat_template_version: 2014-10-16

description: >
  Modify haproxy

# Note extra parameters can be defined, then passed data via the
# environment parameter_defaults, without modifying the parent template
parameters:
  servers:
    type: json
  DeployIdentifier:
    type: string

resources:

  ControllerHaproxyPostConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
        - name: ACTION
        - name: DEPLOY_UUID
      config: {get_file: haproxy-post.sh}

  ControllerHaproxyPostConfigDeploymentsCreate:
    type: OS::Heat::SoftwareDeployments
    properties:
      servers:  {get_param: servers}
      config: {get_resource: ControllerHaproxyPostConfig}
      actions: ['CREATE'] # Only do this on CREATE and UPDATE
      input_values:
        ACTION: 'CREATE'
        DEPLOY_UUID: { get_param: DeployIdentifier }

  ControllerHaproxyPostConfigDeploymentsUpdate:
    type: OS::Heat::SoftwareDeployments
    properties:
      servers:  {get_param: servers}
      config: {get_resource: ControllerHaproxyPostConfig}
      actions: ['UPDATE'] # Only do this on CREATE and UPDATE
      input_values:
        ACTION: 'UPDATE'
        DEPLOY_UUID: { get_param: DeployIdentifier }

outputs:
  deploy_stdout:
    description: Deployment reference, used to trigger puppet apply on changes
    value: 
      list_join:
        - ""
        - - {get_attr: [ControllerHaproxyPostConfigDeploymentsCreate, deploy_stdout]}
          - {get_attr: [ControllerHaproxyPostConfigDeploymentsUpdate, deploy_stdout]}
